name: Trivy Scan

on:
  push:
    branches: [deploy]
  pull_request:

jobs:
  trivy:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build --network=host -t your-image-name:latest .

      - name: Run Trivy in Docker and save SARIF
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd):/root/.cache/ \
            aquasec/trivy image \
              --format sarif \
              -o trivy-results.sarif \
              your-image-name:latest

      - name: Upload SARIF file to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
